name: Fast Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.npm
                      .next/cache
                  key:
                      ${{ runner.os }}-cache-${{
                      hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-cache-

            - name: Install deps
              run: npm ci

            - name: Build standalone
              run: npm run build

            - name: Package standalone
              run: |
                  mkdir deploy
                  cp -r .next/standalone/* deploy/

            - name: Deploy to deployments branch
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"

                  git checkout deployments || git checkout -b deployments
                  rm -rf ./*
                  cp -r $GITHUB_WORKSPACE/deploy/* .
                  git add .
                  git commit -m "Deploy" || echo "No changes"
                  git push origin deployments --force --depth=1
